sudo: required
dist: trusty
services:
  - docker
jobs:
  include:
    - stage: common
      name: "Verify common files are consistent"
      script:
        - git remote add -f b https://github.com/w3c/json-ld-wg.git
        - git remote update
        - git diff --exit-code remotes/b/master -- common
    - stage: examples
      name: "Verify examples are consistent"
      language: ruby
      rvm: 2.5
      bundler_args: --without debug
      script: "rake test"
    - stage: links
      name: "Check internal links"
      script:
        - docker pull stupchiy/checklink
        - docker run -it stupchiy/checklink -b -X '(http|https|mailto):' "https://labs.w3.org/spec-generator/?type=respec&url=https://rawgit.com/w3c/json-ld-api/${TRAVIS_BRANCH}/index.html?specStatus=WD;shortName=json-ld11-api"
    - stage: echidna
      name: "Echidna Publication"
      # Only on push to "publications" branch
      if: branch = publications AND type = push
      env:
        - URL="http://w3c.github.io/json-ld-api/ECHIDNA"
        - DECISION="https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-09-28-json-ld#resolution2"
        - TOKEN: "11657711435bb82ee2493813.74388089"
      script:
        - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
